site_caplo/site_Caplogy/src/Formations/urls.py
from django.urls import path

from .views import recherche, liste_formations, detail_formation, payment_process, payment_success, payment_cancelled, \
    payment_error, create_checkout_session, archive_view

urlpatterns = [

    path('', recherche, name='recherche'),
    path('liste/<str:nom_formation>/', liste_formations, name='liste_formations'),
    path('course/<int:id>/', detail_formation, name='detail_formation'),

    path('archive/<int:category_id>/', archive_view, name='archive'),


    path('create-checkout-session/<int:id>/', create_checkout_session, name='create_checkout_session'),
    path('payment_process/<int:id>/', payment_process, name='payment_process'),
    path('payment_success/<int:id>/', payment_success, name='payment_success'),
    path('payment_cancelled/', payment_cancelled, name='payment_cancelled'),
    path('payment_error/', payment_error, name='payment_error'),



]

site_caplo/site_Caplogy/src/src/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static





urlpatterns = [
    path('admin/', admin.site.urls),
    path('recherche/', include("Formations.urls"), name="formations"),
    path('certifications/', include("Certifications.urls"), name="certifications"),
    path('home/', include("Home.urls"), name="home")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

site_caplo/site_Caplogy/src/Formations/models.py
from datetime import datetime

from django.db import models
from django.urls import reverse


# Create your models here.


class Categories(models.Model):
    nom=models.CharField(max_length=100)

    def __str__(self):
        return self.nom

class Formateur(models.Model):
    nom = models.CharField(max_length=100)
    specialite = models.CharField(max_length=200)
    image = models.ImageField(upload_to='fichiers/')
    linkedin = models.URLField(blank=True)
    article=models.URLField(blank=True)

    def __str__(self):
        return self.nom



class FormationAVenir(models.Model):
    titre = models.CharField(max_length=200)
    lieu = models.CharField(max_length=200)
    date = models.DateField(null=True, blank=True)
    heure_debut = models.TimeField(default='00:00:00')
    heure_fin = models.TimeField(default='00:00:00')
    image = models.ImageField(upload_to='fichiers/')
    categorie = models.ManyToManyField(Categories)
    description = models.TextField(default='')
    prix=models.DecimalField(max_digits=10, decimal_places=2)
    inscri_deadline = models.DateField(null=True, blank=True)
    heure_deadline=models.TimeField(default='00:00:00')
    organisateurs=models.CharField(max_length=200, default='')
    email = models.EmailField(max_length=254, blank=True, null=True)
    linkedin = models.URLField(blank=True)
    google_agenda = models.URLField(blank=True)
    yahoo = models.URLField(blank=True)
    outlook = models.URLField(blank=True)
    objectifs= models.TextField(default='')
    public_visé=models.TextField(default='')
    Positionnement=models.TextField(default='')
    organisation=models.TextField(default='')
    methode=models.TextField(default='')
    validation=models.TextField(default='')
    sanction=models.TextField(default='')
    prérequis=models.TextField(default='')
    formateurs = models.ManyToManyField(Formateur)
    dates_et_lieu_description=models.TextField(default='')
    informations_pratiques=models.TextField(default='')
    Formations_formationavenir_formations_connexes=models.ManyToManyField('self', blank=True, related_name='formations_connexes_set')

    def __str__(self):
        return self.titre
    def get_formateurs_list(self):
        return list(self.formateurs.all())


class DateFormation(models.Model):
    formation = models.ForeignKey(FormationAVenir, on_delete=models.CASCADE, related_name='dates')
    date = models.DateField()
    heure_debut = models.TimeField(default='00:00:00')
    heure_fin = models.TimeField(default='00:00:00')
    lieu = models.CharField(max_length=200)
    inscription_deadline = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.date} - {self.lieu}"

    def get_detail_repetee_url(self):
        return reverse('detail_formation_repetee', args=[self.id])


class Paiement(models.Model):
    formation = models.ForeignKey(FormationAVenir, on_delete=models.CASCADE)
    payer_id = models.CharField(max_length=255)
    payment_id = models.CharField(max_length=255)
    montant = models.DecimalField(max_digits=10, decimal_places=2)
    statut = models.CharField(max_length=50)
    date_paiement = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Paiement {self.payment_id} pour {self.formation.titre}"




class ProgrammeFormation(models.Model):
    formation = models.ForeignKey(FormationAVenir, on_delete=models.CASCADE)
    jour = models.DateField()
    titre_jour = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.formation.titre} -  {self.titre_jour}"

class Module(models.Model):
    programme = models.ForeignKey(ProgrammeFormation, on_delete=models.CASCADE)
    titre = models.CharField(max_length=200)
    heure_debut = models.TimeField()
    heure_fin = models.TimeField()
    description = models.TextField()

    def __str__(self):
        return self.titre






    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse('formations:detail_formation', args=[str(self.id)])






class Avis(models.Model):
    formation= models.ForeignKey(FormationAVenir, on_delete=models.CASCADE)
    commentaire=models.TextField(default='')
    note=models.IntegerField(default=0)

    def __str__(self):
        return f"Avis_sur -  {self.formation}"





class BilletAchat(models.Model):
    formation = models.ForeignKey(FormationAVenir, on_delete=models.CASCADE)
    titre=models.CharField(max_length=200, default='')
    quantité= models.PositiveIntegerField()
    additional_option = models.BooleanField(default=False)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    date_achat= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"billet d'achat pour {self.formation.titre} - {self.quantité} tickets"

site_caplo/site_Caplogy/src/Formations/forms.py
from django import forms


from .models import FormationAVenir, DateFormation


class RechercheFormation(forms.Form):
    nom_formation = forms.ModelChoiceField(FormationAVenir.objects.all(), required=True, label='choisir votre formation')
    formation_id = forms.IntegerField(widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        super(RechercheFormation, self).__init__(*args, **kwargs)
        self.fields['nom_formation'].widget.attrs.update({'class': 'search-bar', 'placeholder': 'Rechercher...'})


class DateFormationForm(forms.ModelForm):
    class Meta:
        model = DateFormation
        fields = ['date', 'lieu', 'inscription_deadline']

site_caplo/site_Caplogy/src/Formations/views.py
import logging
from calendar import monthcalendar
from datetime import date

import stripe
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse


from .forms import RechercheFormation
from .models import FormationAVenir, ProgrammeFormation, BilletAchat, Avis, Paiement, Categories, DateFormation

import paypalrestsdk

from django.conf import settings
#stripe
stripe.api_key = settings.STRIPE_SECRET_KEY
YOUR_DOMAIN = 'http://http://127.0.0.1:8000'

#Configuration du SDK PayPal
paypalrestsdk.configure({
    "mode":"sandbox",   # Sandbox ou live
    "client_id":settings.PAYPAL_CLIENT_ID,
    "client_secret":settings.PAYPAL_CLIENT_SECRET,
})


def recherche(request):

    if request.method == 'POST':
        form = RechercheFormation(request.POST)
        if form.is_valid():
            nom_formation = form.cleaned_data.get('nom_formation')

            url = reverse('liste_formations', kwargs={'nom_formation': nom_formation})
            return HttpResponseRedirect(url)
    else:
        form=RechercheFormation()

    return render(request, 'recherche.html', {'form':form,})
def liste_formations(request, nom_formation):
    formations = FormationAVenir.objects.filter(titre=nom_formation)
    return render(request, 'liste_formation.html', {'formations': formations, 'nom_formation': nom_formation})








def detail_formation(request, id):
    formation = get_object_or_404(FormationAVenir, id=id)
    programmes = ProgrammeFormation.objects.filter(formation=formation).order_by('jour')
    formateurs = formation.get_formateurs_list()
    billets = BilletAchat.objects.filter(formation=formation)
    categories = formation.categorie.all()

    if request.method == 'POST':
        note = request.POST.get('rating')
        commentaire = request.POST.get('commentaire')

        if note and commentaire:
            try:
                note = int(note)
                if 1 <= note <= 5:  # Validation simple de la note
                    Avis.objects.create(
                        formation=formation,
                        note=note,
                        commentaire=commentaire
                    )
                    return HttpResponseRedirect(request.path_info)
                else:

                    pass
            except ValueError:
                # Gérer une note non numérique
                pass

    context = {
        'formation': formation,
        'programmes': programmes,
        'formateurs': formateurs,
        'billets': billets,
        'avis': Avis.objects.filter(formation=formation),
        'categories': categories,
    }

    return render(request, 'detail_formation.html', context)







def archive_view(request, category_id):
    # Récupérer la catégorie
    categorie = get_object_or_404(Categories, id=category_id)


    # Récupérer les formations expirées pour la catégorie donnée
    formations_expirees = FormationAVenir.objects.filter(
        categorie=categorie,
        date__lt=date.today()
    )

    # Extraire les titres des formations expirées
    noms_formations_expirees = formations_expirees

    context = {
        'noms_formations_expirees': noms_formations_expirees,
        'categorie_nom': categorie.nom,  # Ajouter le nom de la catégorie au contexte

    }

    return render(request, 'archive.html', context)

def payment_process(request, id):
    formation = get_object_or_404(FormationAVenir, id=id)
    prix = formation.prix

    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 1))  # Récupérer la quantité du formulaire
        total_price = prix * quantity

        logging.info(f"Quantity: {quantity}, Total Price: {total_price}")

        payment = paypalrestsdk.Payment({
            "intent": "sale",
            "payer": {
                "payment_method": "paypal"},
            "redirect_urls": {
                "return_url": request.build_absolute_uri(reverse('payment_success', args=[formation.id])),
                "cancel_url": request.build_absolute_uri(reverse('payment_cancelled'))},
            "transactions": [{
                "item_list": {
                    "items": [{
                        "name": formation.titre,
                        "sku": formation.id,  # Stock Keeping Unit
                        "price": str(prix),
                        "currency": "EUR",
                        "quantity": quantity}]},
                "amount": {
                    "total": str(total_price),
                    "currency": "EUR"},
                "description": f"Payment for {quantity} * {formation.titre}"}]})

        if payment.create():
            for link in payment.links:
                if link.rel == "approval_url":
                    approval_url = str(link.href)
                    return redirect(approval_url)
        else:
            logging.error(payment.error)
            return redirect('payment_error')
    else:
        return redirect('payment_error')

def payment_success(request, id):
    payment_id = request.GET.get('paymentId')
    payer_id = request.GET.get('PayerID')

    if payment_id and payer_id:
        payment = paypalrestsdk.Payment.find(payment_id)
        if payment.execute({"payer_id": payer_id}):
            # Enregistrer le paiement dans votre modèle
            formation = get_object_or_404(FormationAVenir, id=id)
            montant = float(payment.transactions[0].amount.total)
            Paiement.objects.create(
                formation=formation,
                payer_id=payer_id,
                payment_id=payment_id,
                montant=montant,
                statut=payment.state
            )
            return render(request, 'payment_success.html')
        else:
            logging.error(payment.error)
            return render(request, 'payment_error.html')
    else:
        return redirect('payment_error')


def payment_cancelled(request):
    return render(request, 'payment_cancelled.html')

def payment_error(request):
    return render(request, 'payment_error.html')






def create_checkout_session(request, id):
    formation = get_object_or_404(FormationAVenir, id=id)
    prix = formation.prix * 100  # Convert to cents

    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 1))
        prix_cents = int(prix) # Multiply by quantity

        try:
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=[
                    {
                        'price_data': {
                            'currency': 'eur',
                            'product_data': {
                                'name': formation.titre,
                            },
                            'unit_amount': prix_cents,  # Montant total en cents
                        },
                        'quantity': quantity,
                    },
                ],
                mode='payment',
                success_url=request.build_absolute_uri(reverse('payment_success', args=[formation.id])),
                cancel_url=request.build_absolute_uri(reverse('payment_cancelled')),
            )
            return redirect(checkout_session.url)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=403)

def stripe_payment_success(request, id):
    # Handle the success logic here
    formation = get_object_or_404(FormationAVenir, id=id)

    # Assuming you want to save some payment details in your database
    payment_intent_id = request.GET.get('payment_intent')
    if payment_intent_id:
        payment_intent = stripe.PaymentIntent.retrieve(payment_intent_id)
        amount_received = payment_intent.amount_received / 100  # Convert from cents to euros
        currency = payment_intent.currency
        status = payment_intent.status

        # Enregistrer les détails du paiement dans votre modèle
        Paiement.objects.create(
            formation=formation,
            payer_id=payment_intent.charges.data[0].billing_details.name,
            payment_id=payment_intent.id,
            montant=amount_received,
            statut=status
        )

    return render(request, 'payment_success.html', {'formation': formation})

    # Save payment details if necessary
    return render(request, 'payment_success.html')

def payment_cancelled(request):
    return render(request, 'payment_cancelled.html')

site_caplo/site_Caplogy/src/Formations/templates/archive.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>Archive formations</title>
{% endblock %}

{% block content %}
    <h1 style="text-align:center;">Archive : "{{ categorie_nom }}"</h1>

    <br><br><br>
    <div class="container_liste_formations">
        <div class="formations-container">
            {% for formation in noms_formations_expirees %}
                <div class="formation-item">
                    {% if formation.image %}
                        <img src="{{ formation.image.url }}" alt="{{ formation.titre }}" class="logo">
                    {% endif %}
                    <h2>{{ formation.titre }}</h2>
                    <p><img src="{% static 'logo_et_fichier_caplogy/lieu.png' %}" style="max-width: 19px;"><strong>  Lieu : {{ formation.lieu }}</strong></p>

                    <p><img src="{% static 'logo_et_fichier_caplogy/calender.png' %}" style="max-width: 19px;">  Date: {{ formation.date|date:"d/m/Y" }}</p>
                    <button type="submit" >Achat expiré</button>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/script.js' %}"></script>
{% endblock %}

site_caplo/site_Caplogy/src/Formations/templates/liste_formation.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    <title>Liste des Formations</title>
{% endblock %}

{% block content %}
    <h1 style="text-align:center;">Résultat de recherche pour: "{{ nom_formation }}"</h1>

    <br><br><br>
    <div class="container_liste_formations">
        <div class="formations-container">
            {% for formation in formations %}
                <div class="formation-item">
                    {% if formation.image %}
                        <img src="{{ formation.image.url }}" alt="{{ formation.titre }}" class="logo">
                    {% endif %}
                    <h2>{{ formation.titre }}</h2>
                    <p><img src="{% static 'logo_et_fichier_caplogy/lieu.png' %}" style="max-width: 19px;"><strong>  Lieu : {{ formation.lieu }}</strong></p>

                    <p><img src="{% static 'logo_et_fichier_caplogy/calender.png' %}" style="max-width: 19px;">  Date:{{formation.date|date:"d/m/Y" }}</p>
                    <button type="submit"  onclick="redirectToPage('{% url 'detail_formation' formation.id %}')">Réserver votre place</button>
                </div>
            {% empty %}
                <p>Aucune formation trouvée avec le titre "{{ nom_formation }}"</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/script.js' %}"></script>


{% endblock %}

site_caplo/site_Caplogy/src/Formations/templates/payment_cancelled.html
{% extends 'base.html' %}

{% block title %}
    <title>Paiement annulé</title>
{% endblock %}

{% block content %}
    <h1> Payement annulé </h1>
    <p>Votre paiement a été annulé.</p>

{% endblock %}

site_caplo/site_Caplogy/src/Formations/templates/payment_error.html
{% extends 'base.html' %}

{% block title %}
    <title>erreur de payment</title>
{% endblock %}

{% block content %}
    <h1>Erreur de paiement </h1>
    <p>Une erreur s'est produite lors du traitement de votre paiement. Veuillez réessayer.</p>

{% endblock %}

site_caplo/site_Caplogy/src/Formations/templates/payment_success.html
{% extends 'base.html' %}

{% block title %}
    <title>Paiement réussi</title>
{% endblock %}

{% block content %}
    <h1> Le paiement a été effectué avec succès</h1>
    <p>Merci pour votre achat de la formation {{ formation.titre }}.</p>

{% endblock %}

site_caplo/site_Caplogy/src/Formations/templates/recherche.html
{% extends 'base.html' %}

{% load static %}

{% block title%}
    <title>Recherche Formation</title>
{%endblock%}


{%block content%}
    <br>
    <br>

    <h1 style="text-align:center;">Trouver Votre Formation</h1>
    <div class="search-container">
        <form method="POST">
            {% csrf_token %}
            {{ form.nom_formation }}
            <input type="hidden" name="formation_id" id="id_formation_id" value="{{ form.nom_formation.value }}">
            <button type="submit">Rechercher</button>
        </form>
    </div>

    <br><br>

<div>
    <h1 style="text-align:center;">Nos Partenaires</h1>
    <br>
    <div id="les-partenaires" style="background:white;">
        <img src="{% static 'logo_et_fichier_caplogy/caplogy_education.png' %}" alt="Caplogy_education" class="logo item-partenaire">
        <img src="{% static 'logo_et_fichier_caplogy/microsoft_logo.png' %}" alt="microsoft_logo" class="logo item-partenaire">
        <img src="{% static 'logo_et_fichier_caplogy/ec_council_logo.png' %}" alt="ec_council_logo" class="logo item-partenaire">
        <img src="{% static 'logo_et_fichier_caplogy/iso-logo.png' %}" alt="iso_logo" class="logo item-partenaire">
        <img src="{% static 'logo_et_fichier_caplogy/amazon_web_logo.png' %}" alt="amazon_web_logo" class="logo item-partenaire">
        <img src="{% static 'logo_et_fichier_caplogy/its-logo.png' %}" alt="its_logo" class="logo item-partenaire">
        <img src="{% static 'logo_et_fichier_caplogy/cisco-logo.png' %}" alt="cisco_logo" class="logo item-partenaire">
    </div>
</div>

    <br><br>

    <div>
        <h1 style="text-align:center;">Nos prochaines formations</h1>
    </div>

    <br>


<br><br><br>

    <div style="    display: flex; justify-content: center; ">
        {% for formation in formations_avenir %}
            <div style="display: inline-block; margin:20px">
                {% if formation.image %}
                    <img src="{{ formation.image.url }}" alt="{{ formation.titre }}" class="logo">
                {% endif %}
                <h2 >{{ formation.titre }}</h2>
                <p><img src="{% static 'logo_et_fichier_caplogy/lieu.png' %}" style="max-width: 19px;"> <strong > Lieu : {{ formation.lieu }}</strong></p>

                <p><img src="{% static 'logo_et_fichier_caplogy/calender.png' %}" style="max-width: 19px;">  Date:{{formation.date|date:"d/m/Y" }}</p>
                <button type="submit"  onclick="redirectToPage('{% url 'detail_formation' formation.id %}')">Réserver votre place</button>



            </div>
        {% endfor %}

    </div>

<br><br>
    <div>
        <div><h1 style="text-align:center;">Accompagnez votre formation par une certification professionnelle </h1></div>
        <br><br>
        <div><button onclick="redirectToPage('{% url 'liste_certifications' %}')" style="display: block; margin: 0 auto; position: absolute;  left: 50%; transform: translate(-50%, -50%);">Boutique des certifications</button></div>
    </div>

    <br><br><br>

    <div>







<br><br><br><br><br>

{% endblock %}


{% block scripts %}
    <script src="{% static 'js/script.js' %}"></script>


{% endblock %}